<a href="https://colab.research.google.com/github/akshitaasaxena/python-ds/blob/main/DAY_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1
import numpy as np # np is a user defined nickname, alias
# a = alias_name.function
a= np.array([1,3,9,0,2])

# a= numpy.array([])
print (a)

[1 3 9 0 2]


In [2]:
a = np.array ([1,2,3,'4'])
print(a) # converts all the elements to string

['1' '2' '3' '4']


In [3]:
#QUESTION 2

np_arr=np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1])) #wherever there is value, boolean conversion will result into true.

a=False
print(bool(a))

a=0
print(bool(a))


True
False
False


In [4]:
a= np.zeros(5)
print (a)

b=np.zeros((2,3)) #shape passed as list or tuple
print(b)

c=np.zeros((2,3,4))
print(c)
print(type(c[0][0][0])) #<class 'numpy.float64'>

#to have a specific datatype
d=np.zeros((2,3,4),dtype=int)
print(type(d[0][0][0])) #<class 'numpy.int64'>

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>
<class 'numpy.int64'>


In [5]:
a = np.empty(4,dtype=int)
print(a) #[ 368611571          0         46 4294967296]

[547699846         0         2        -1]


In [6]:
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [7]:
a = np.arange(5) # single parameter will be taken as stop
print(a)

b = np.arange(3,12,4,dtype=int) # start,stop,step => exclusive of the stop
print(b)

[0 1 2 3 4]
[ 3  7 11]


In [8]:
c = np.linspace(5,10,3,dtype=int, endpoint = False) # start, stop, number of values
# here endpoint is included, need to manually turn it to false
print(c)

[5 6 8]


In [10]:
a = np.ones((2,3),dtype=int)
print(a)

print(np.shape(a)) # tells abput the dimension

print(np.size(a)) # total number of elements

# print(np.dtype(a))

[[1 1 1]
 [1 1 1]]
(2, 3)
6


In [11]:
a = np.random.randint(8,10,5)
print(a)

[9 9 9 8 9]


In [12]:
a = np.random.choice([2,3,5,8],2) # choice from a particular array , passed the list and choosing random values from it
print(a)

[8 5]


In [13]:
a = np.ones((3,3), dtype = int)
b = np.ones((3,3), dtype = int)
print (a)
print(a*2)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
# elements at corresponding positionn are being operated.

c=np.ones((2,2), dtype=int)
# print(a+c) -> ValueError : operands could not be broadcast together with different shapes

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
a = [2,3,4]
print(a*2) # prints the list twice

[2, 3, 4, 2, 3, 4]


In [15]:
a = np.random.randint(2,15,6)
print(a)
b = a.reshape((3,2))
print(b)

[12  2  3 11 10 14]
[[12  2]
 [ 3 11]
 [10 14]]


In [16]:
a = np.random.randint(2,16,8)
b = a.reshape((2,4))
print(b)

c=b.transpose()
print(c)

a = np.random.randint(2,16,8)
e = a.reshape((2,4))
print(e)

d = np.concatenate((b,e),axis=1) #
print(d)

[[ 9 13  6 13]
 [ 9  5 14 12]]
[[ 9  9]
 [13  5]
 [ 6 14]
 [13 12]]
[[ 8 15 11 15]
 [ 6  2  3  2]]
[[ 9 13  6 13  8 15 11 15]
 [ 9  5 14 12  6  2  3  2]]


In [17]:
a = np.random.randint(2,16,8)
print(a)
b = np.random.randint(2,16,8)
print(b)

c = np.where(b > 2, b, a)
print(c)

[13 10 11 13  3  7 12  9]
[14  5 10 14 13 12  7 15]
[14  5 10 14 13 12  7 15]


In [18]:
a = np.random.randint(2,16,8)
print(a)
b = np.sort(a)
print(b)

[ 7 13  7  3  6  7  6 15]
[ 3  6  6  7  7  7 13 15]


In [19]:
a = np.random.randint(2,16,8)
print(a)
b = np.sum(a)
print(b)

[12  8 13  4  5  9  7  4]
62


In [20]:
a = np.random.randint(2,16,8)
print(a)
b = np.mean(a)
print(b)

[14  5  7  6  3  6 10 10]
7.625


In [21]:
a = np.random.randint(2,16,8)
print(a)
b = np.std(a) # standard deviation
print(b)

[10 15  6 14 13  7 15 15]
3.4798527267687636


In [22]:
a = np.random.randint(2,16,8)
print(a)
b = np.min(a)
print(b)

[ 4  7 12 10  5 10 15 15]
4


In [23]:
a = np.random.randint(2,16,8)
print(a)
b = np.max(a)
print(b)

[11 11  9 12 13 14  4  3]
14


In [24]:
a = np.random.randint(2,16,8)
print(a)
b = np.unique(a)
print(b)

[13  3  9 13  9  4 14  3]
[ 3  4  9 13 14]


In [25]:
a = np.random.randint(2,16,8)
a = a.reshape((2,4))
print(a)

b = np.random.randint(2,16,8)
b = b.reshape((4,2))
print(b)

c = np.matmul(a,b)
print(c)

[[ 4 15 11  2]
 [ 5  7 11 14]]
[[ 3  6]
 [15  9]
 [ 5  3]
 [ 8  6]]
[[308 204]
 [287 210]]


In [26]:
scores = input()
# scores = np.random.randint(0,100,7)
scores = scores.split()
# scores =[int(x) for x in scores] -> another way to convert in integer
scores = list(map(int,scores))
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]
scores = np.array(scores)
for i in range (len(scores)):
  print(scores[i],days[i])
print("maximum score : ", np.max(scores), "on ", days[np.argmax(scores)])
print("minimum score : ", np.min(scores), "on ", days[np.argmin(scores)])
print("sum of scores : ", np.sum(scores))
print("mean of scores : ", np.mean(scores))
print("standard deviation of scores", np.std(scores))

100 99 56 78 0 12 34 
100 MON
99 TUES
56 WED
78 THURS
0 FRI
12 SAT
34 SUN
maximum score :  100 on  MON
minimum score :  0 on  FRI
sum of scores :  379
mean of scores :  54.142857142857146
standard deviation of scores 37.418210125279806


In [ ]:
scores = []
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]

for i in range (7):
  x=input(f'give the input for the {days[i]}: ') #fstring : variables inside a string


In [ ]:
#Question 1
a = np.array([3,3,3,3])
b = a
b[0] = 1
a[-1]=6
print(a,b)

# HW

In [ ]:
n=int(input())
items=[]
prices=[]
for i in range(1,n+1):
  x=input(f'enter item number {i}:')
  y=int(input(f'enter the price for item {x} :'))
  items.append(x)
  prices.append(y)
prices = np.array(prices)
for i in range (len(prices)):
  print(items[i]," ",prices[i])
print("maximum price : ", np.max(prices), "of ", items[np.argmax(prices)])
print("minimum price : ", np.min(prices), "of ", items[np.argmin(prices)])
print("sum of all the prices : ", np.sum(prices))
print("mean of all the prices : ", np.mean(prices))
print("standard deviation of prices : ", np.std(prices))