<a href="https://colab.research.google.com/github/akshitaasaxena/python-ds/blob/main/day_5(panda).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#QUES-1-numpy
import numpy as np
y=np.random.randint(1,91,size=(5,5))
#mean row wise:
j=np.mean(y.mean(axis=1))
print(j)
p=np.mean(y.mean(axis=0))
print(p)
m=np.where(y%2==0,-1,y)
print(m)
#sort column and row
h=np.sort(m,axis=1)
g=np.sort(m,axis=0)
print(h)
print(g)
rowsm=m.sum(axis=1)
colsm=m.sum(axis=0)
print(rowsm,colsm)
#count(-ves) using count
count_col=np.sum(np.where(m<0,1,0))
print(count_col)

44.96000000000001
44.96
[[-1 -1 29 -1 19]
 [39 31 -1 11 51]
 [33 35 53 -1 39]
 [25 25 21 -1  1]
 [-1 69  5 65 85]]
[[-1 -1 -1 19 29]
 [-1 11 31 39 51]
 [-1 33 35 39 53]
 [-1  1 21 25 25]
 [-1  5 65 69 85]]
[[-1 -1 -1 -1  1]
 [-1 25  5 -1 19]
 [25 31 21 -1 39]
 [33 35 29 11 51]
 [39 69 53 65 85]]
[ 45 131 159  71 223] [ 95 159 107  73 195]
[2 1 1 3 0]
7


In [19]:
#ques-2-numpy
stock=np.random.randint(20,101,size=(5,5))
demand=np.random.randint(1,101,size=(5,5))
remstock=stock-demand
print(remstock)
totalshortage=abs(np.sum(np.where(remstock<0,remstock,0),axis=1)) #abs for converting negative values to positive ones.
print(totalshortage)
replace=np.where(remstock<0,0,remstock)
print(replace)
zerostock=np.sum(np.where(replace==0,1,0),axis=1)
print(zerostock)
sort=np.sort(zerostock)

[[-70   2  88  49   2]
 [-30 -64  53  41   8]
 [-41 -50   9 -61 -68]
 [ 22  63   1  27  -2]
 [  1  52 -14   9 -11]]
[ 70  94 220   2  25]
[[ 0  2 88 49  2]
 [ 0  0 53 41  8]
 [ 0  0  9  0  0]
 [22 63  1 27  0]
 [ 1 52  0  9  0]]
[1 2 4 1 2]


# PANDAS

In [29]:
import pandas as pd
h=pd.read_csv("./student_data.csv",sep=',')
#print(h)
print(h.head())#gives 5 rows from start
print(h.head(6))#gives 6 rows from start
print(h.tail(5))

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60          